version: '3'

services:
  web:
    restart: always
    build: 
      context: ./web
    environment:
      - APP_CONFIG = configs.DevelopmentConfig
    ports:
      - "8000:8000"
    command: /usr/local/bin/python main.py
