version: '3'
#archivo originalmente creado para utilizar con Compose

services:
  web:
    restart: always
    build:
      context: ./web
    networks:
      - front-tier
      - back-tier
    expose:
      - "8000"
    volumes:
      - "static:/app/web/static"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 main:app
    depends_on:
      - postgres

  nginx:
    restart: always
    build:
      context: ./nginx
    networks:
      - front-tier
    ports: 
      - "80:80"
    volumes:
      - "static:/www/static"
    depends_on:
      - web
 
  postgres:
    restart: always
    build:
      context: ./postgres

    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    expose:
      - "5432"

volumes:
  db-data:
  static:

networks:
  front-tier:
  back-tier: