version: '3'
#configurado para deploy en swarm, es necesario generea las imagenes manualmente

services:
  web:
    image: web:test
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    environment:
      - APP_CONFIG = ExtendedConfig
    command: ["/usr/local/bin/gunicorn", "-w", "2", "-b", ":8000", "main:app"]
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres:test
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data: