version: '3'
#configurado para deploy en swarm, es necesario generea las imagenes manualmente

services:
  web:
    image: web:test
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    networks:
      - front-tier
      - back-tier
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    image: postgre:test
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier: