version: '3'

services:
  jenkins:
    image: jenkins-docker
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
          - node.hostname==srv-manager-001
      restart_policy:
        condition: on-failure
    volumes:
      - "/root/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8090:8080
      - 50000:50000
    networks:
      - jenkins

networks:
  jenkins:
